jwt:
  accessTokenSecret: "testKeytestKeytestKeytestKeytestKeytestKeytestKeytestKeytestKeytestKeytestKeytestKeytestKeytestKeytestKeytestKeytestKeytestKeytestKeytestKeytestKey"
  accessTokenExpiredSeconds: 86400
  refreshTokenSecret: "testKeytestKeytestKeytestKeytestKeytestKeytestKeytestKeytestKeytestKeytestKeytestKeytestKeytestKeytestKeytestKeytestKeytestKeytestKeytestKeytestKeyt"
  refreshTokenExpiredSeconds: 2592000
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 20055ec2fb5a4bc7bd11a8b44fb57c9e
            client-secret: NixkKc6SexTZfHCUcLZ5YA0miEIU1wEg
            scope:
              - profile_nickname
              - profile_image
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          format_sql: true
          show_sql: true

